version: "3"
services:
  web:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "5001:5001"
  client:
    build:
      args:
        HOSTNAME: 'web'
      context: .
      dockerfile: client.Dockerfile
    depends_on:
      - web
    links:
      - web
